### ISSUE TITLE
Crypto Messages Sizes

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#167]
Problems to discuss:
* What are the sizes of the keys, hashes and fingerprints?
* How can we keep the messages small?
* Public messages are very short, they are flooded through the network and shall be signed. 
  * The signature needs to be very small. 
  * At the moment the signature size is 512B, the message size is only 140B (this doesn't really make sense IMHO)
  * Could we just use a hash?

Sizes:
* Pubkey 16KB
* Fingerprint  64B
* Signature 512B
* Signature hash 32B

Messages:
* User hello message: As this message get's spread across the network, we should keep it small.
  * Msg type
  * user name
  * fingerprint
* Signed public message
  * Msg type
  * ? user name ? 
  * Fingerprint
  * Message
  * Signature / Hash
* Encrypted private message
  * Msg type
  * ? user name ?
  * Fingerprint
  * Encrypted message

**Comment by spacekookie** [comment]
First, I don't think arbitrarily limiting message sizes to 140 character (like twitter) is actually that useful for communication. We should have a maximum message length but I'd say something along the lines of 500 (512 for nice power of 2 :) ) character (like mastodon) is more useful.

Secondly, when it comes to identifying a user we could just send their fingerprint in a public message. That is a 64B hash. However that doesn't really say anything about the authenticity of the message.

If network load is a **major** concern in public message flooding I would suggest we remove the signature from a public message and let users in the UI know that a message was "unverified". Then clicking a "verify" button in the UI would fetch the message signature explicitly for that one message at which point a client would flood a signed message to everybody.

This means that messages are only signed in a public timeline if one user in said network wants it to be verified.

Private messages should always be signed and encrypted and because they're not flooded I don't think that'll cause a lot of network load.

Additionally: we can't reduce the signature size because of *maths* :P In short, for a signed message we need to accept a baseline size of 512B. The problem with using a signature hash (so basically an hmac) is that those algorithms use symmetric keys which isn't really plausible for an asymmetric signature verification process.
