### ISSUE TITLE
[MacOS] Malformed config file on new libqaul version

### ISSUE THREAD

**Issue by brenodt** [qaul/qaul.net#372]
When attempting to run the new library version on MacOS, if a previous version has been installed, the following error may be thrown:
```
thread '<unnamed>' panicked at 'Couldn't Convert to `Configuration`, malformed config file.: missing field `routing`', libqaul/src/storage/configuration.rs:199:18
```

Whenever that happens, removing the current *config.yaml* file fixes the issue.

I believe libqaul should either migrate the critical information (username and so on) to a new configuration, or remove the obsolete one by itself.

**Comment by MathJud** [comment]
This behaviour is known and has no fix at the moment, as the structure of the configuration file is statically typed in libqaul and whenever the structure of it changes, this error will appear.

The same thing goes for the data base where no migration is offered in the beta phase.

A workaround for this bug is to remove the configuration and the data base manually whenever this happens.

For now - the beta version - I'm OK with this behaviour. For a stable version we will need to implement an upgrading mechanism.
