### ISSUE TITLE
[Desktop] No security number generated

### ISSUE THREAD

**Issue by cinorid** [qaul/qaul.net#431]
![image](https://user-images.githubusercontent.com/10947730/195981658-1e81014e-0456-471a-84c2-3c4a0857f12a.png)

**Comment by MathJud** [comment]
Thanks for the bug report.
Unfortunately the latest windows build is broken.
We are working on a fix.

**Comment by cinorid** [comment]
@MathJud I confirm the problem has been fixed.

**Comment by MathJud** [comment]
The latest build should fix all issues.

Please make sure to manually delete the following configuration folder:
`AppData\Roaming\qaul` in your home directory

fixed by #8dee0a8c865b55c251f640130c4c0aa782f290e5
Download build: https://github.com/qaul/qaul.net/releases/tag/v2.0.0-beta.4%2B782-flutter
