### ISSUE TITLE
Automatic back-swipe to "public messaging" screen when entry field is open.

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#558]
When when swiping away from the public messaging screen, it will automatically keep swiping back to it, if the entry field to enter a new public message is open.

How to reproduce this bug:

1) open the "public chat" window on Android
2) open the entry field to create a public note.
3) while the entry  field is open, swipe over the the next screen.
4) Result: it will automatically swipe back.

This bug was reported by a user of a qaul testing-workshop. Thanks!

**Comment by brenodt** [comment]
Do you know what Android version they're on?

I couldn't reproduce locally, but I believe it has to do with the OS version:
https://github.com/qaul/qaul.net/assets/54450520/c7937e24-8712-4c94-a8b3-00572dc33ab3

In any case, what would be the expected behavior? I see two options:
- we prevent swiping to adjacent tabs whilst the keyboard is active
- we automatically dismiss the keyboard on horizontal swipe

**Comment by MathJud** [comment]
The phone on which I tested, and for which I confirm the bug is Android 12.

**Comment by MathJud** [comment]
> In any case, what would be the expected behavior? I see two options:
> 
>     * we prevent swiping to adjacent tabs whilst the keyboard is active
> 
>     * we automatically dismiss the keyboard on horizontal swipe

Will we lose the content, if we dismiss the keyboard?
