### ISSUE TITLE
Beta 18 prerelease Testing

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#623]
While testing the beta 18 pre-release the following things appeared:

- Android
    - [x] The new configuration used the `TCP` address for the Community Node, instead of the new `QUIC` address.
- [x] Network View
    -  the network was not filtering the results and showed the same result on each filter-option.
    - instead of the shortest path it always took the longest path.

**Comment by MathJud** [comment]
The Network View

<img width=250 src="https://github.com/qaul/qaul.net/assets/1871891/3964741a-ed0f-45a9-8117-8ea93776ee0d" />
<img width=250 src="https://github.com/qaul/qaul.net/assets/1871891/8866765f-e9bc-4037-a3c8-470a405a2590" />
<img width=250 src="https://github.com/qaul/qaul.net/assets/1871891/b96ac396-71eb-4e5d-98f6-ff58d482d5da" />
<img width=250 src="https://github.com/qaul/qaul.net/assets/1871891/5143f955-4991-4d25-9819-68ecdc6497e4" />

**Comment by MathJud** [comment]
New Internet Node / Community Node

<img width=250 src="https://github.com/qaul/qaul.net/assets/1871891/ec41d1a7-c9b5-4480-b575-0d88c2e4b37d" />

**Comment by brenodt** [comment]
As discussed, the reason the default node didn't take the new `quic` protocol format was that the build for Android, iOS and Windows had used the library assets from the latest release.

Since v18 is flagged as `pre-release`, it's not considered the latest.

This is circumvented by specifying the tag on the `gh release download` commands, which has been done via: https://github.com/qaul/qaul.net/commit/1f34972902b5b0b724091fcde1059363341c134b

I triggered a new Flutter build using the new configuration:
https://app.circleci.com/pipelines/github/qaul/qaul.net/1401

And we can see it succeeded, as, on new installs, the default community node uses the new protocol:
<img width=250 src="https://github.com/qaul/qaul.net/assets/54450520/95551866-9d09-4121-90b7-f36290f50556" />
